// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SmartDocumentRAG.API.Data;

#nullable disable

namespace SmartDocumentRAG.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260928154602_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartDocumentRAG.API.Models.ChildChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<Guid>("ParentChunkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentChunkId");

                    b.ToTable("ChildChunks");
                });

            modelBuilder.Entity("SmartDocumentRAG.API.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("SmartDocumentRAG.API.Models.ParentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("ParentChunks");
                });

            modelBuilder.Entity("SmartDocumentRAG.API.Models.ChildChunk", b =>
                {
                    b.HasOne("SmartDocumentRAG.API.Models.ParentChunk", "ParentChunk")
                        .WithMany("ChildChunks")
                        .HasForeignKey("ParentChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentChunk");
                });

            modelBuilder.Entity("SmartDocumentRAG.API.Models.ParentChunk", b =>
                {
                    b.HasOne("SmartDocumentRAG.API.Models.Document", "Document")
                        .WithMany("ParentChunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("SmartDocumentRAG.API.Models.Document", b =>
                {
                    b.Navigation("ParentChunks");
                });

            modelBuilder.Entity("SmartDocumentRAG.API.Models.ParentChunk", b =>
                {
                    b.Navigation("ChildChunks");
                });
#pragma warning restore 612, 618
        }
    }
}
